import { node, html, fig, js, ts, css, bs, react, redux, ex, seq, postg, postm } from "./svg/Technologies";
import { frontDevelop, backDevelop, projects, design, TA, FS, B5, UI, CS, imgCalendly, nursingHRRG, portfolio, dashboard } from "./images/Images";

export {
    node,
    html,
    fig,
    js,
    ts,
    css,
    bs,
    react,
    redux,
    ex,
    seq,
    postg,
    postm,
    TA,
    FS,
    B5,
    UI,
    CS,
    frontDevelop,
    backDevelop,
    projects,
    design,
    imgCalendly,
    nursingHRRG,
    portfolio,
    dashboard,
}